### ISSUE TITLE
error when run

### ISSUE THREAD

**Issue by Pandinhaa11** [sevenc-nanashi/chart_cyanvas#18]
sub-image | 2024-08-26T19:56:38.949400Z  INFO request{method=GET uri=/sonolus/info?localization=en version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=0 ms status=404

**Comment by sevenc-nanashi** [comment]
Wrong server; You have to request to frontend through proxies such as ngrok or cloudflare's tunnel.

**Comment by Pandinhaa11** [comment]
oh ok, how i connect to the proxy with ngrok?

**Comment by sevenc-nanashi** [comment]
I'll write about hosting later

**Comment by Pandinhaa11** [comment]
ok
im waiting

**Comment by Pandinhaa11** [comment]
@sevenc-nanashi
