### ISSUE TITLE
Unable to Join Discord Server

### ISSUE THREAD

**Issue by yayicanfart** [sevenc-nanashi/chart_cyanvas#21]
i was trying to upload a bake no hana chart but when i join the discord to link my account it comes with this error.
![Screenshot 2024-11-09 213958](https://github.com/user-attachments/assets/9c411b2e-fe99-47c4-ba79-bf9428368ed3)

**Comment by sevenc-nanashi** [comment]
idk but I guess you've been banned for ignoring warnings

**Comment by yayicanfart** [comment]
It was my first time joining though?

**Comment by yayicanfart** [comment]
if ive been banned is it permanent?

**Comment by noidesserts** [comment]
is there any way to appeal?
